### ISSUE TITLE
Update wiki with database structure

### ISSUE THREAD

**Issue by marek1840** [marek1840/IOSR2015-facebook-recommendations#2]
Our database nodes are:
* FacebookUser
* FacebookContent

they are connected with edges:
* Knows
* Likes

In such manner:
FacebookUser--[Knows]-->FacebookUser
FacebookUser--[Likes]-->FacebookContent

Nodes are divided in two groups:
* NotAnalized---->FacebookUser
* Analized---->FacebookUser

**Comment by Ping32** [comment]
Ok, we also would like to store, edges that represent similarity of vertices. 
E.g. we would like to know  if "football" is somehow connected with "AC Milan". 

For now I'm not sure, but probably we could store edges that represents entities that are contrastive e.g. fanpages of competing teams.

This edges will be added by analyser.
